add docker file

diff --git a/.github/workflows/CI/CD Pipeline.yml b/.github/workflows/CI/CD Pipeline.yml
--- a/.github/workflows/CI/CD Pipeline.yml
+++ b/.github/workflows/CI/CD Pipeline.yml
@@ -13,8 +13,7 @@ on:
 
 env:
   AWS_REGION: us-east-1
-  IMAGE_NAME: my-app
-  IMAGE_TAG: latest
+  IMAGE_NAME: shopflow
 
 jobs:
 
@@ -158,21 +157,21 @@ jobs:
         run: terraform apply -auto-approve
 
 
-  smoke-test:
-    name: Smoke Test
-    runs-on: ubuntu-latest
-    needs: terraform-apply
+  # smoke-test:
+  #   name: Smoke Test
+  #   runs-on: ubuntu-latest
+  #   needs: terraform-apply
 
-    steps:
-      - name: Test Application
-        run: |
-          curl -f http://YOUR-APP-URL || exit 1
+  #   steps:
+  #     - name: Test Application
+  #       run: |
+  #         curl -f http://YOUR-APP-URL || exit 1
 
-      - name: Rollback on Failure
-        if: failure()
-        run: |
-          echo "Smoke test failed!"
-          echo "Starting rollback..."
+  #     - name: Rollback on Failure
+  #       if: failure()
+  #       run: |
+  #         echo "Smoke test failed!"
+  #         echo "Starting rollback..."
 
-          cd terraform
-          terraform destroy -auto-approve
+  #         cd terraform
+  #         terraform destroy -auto-approve
